### ISSUE TITLE
Initialize HASH_FUNCTION table when the database is created

### ISSUE THREAD

**Issue by gkosm314** [eellak/gsoc2021-hashesDB#20]
This table will contain information about the hash functions supported by hashesDB.
The first version will support the functions provided by the built-in  _hashlib_ module.
It will also support ssdeep fuzzy hash function.

**Comment by gkosm314** [comment]
The _HASH_FUNCTION_ table will be initialized so that it contains all the hash functions of the built-in _hashlib_ python module, plus the fuzzy hashes hashesDB will support. 

The schema of the _HASH_FUNCTION_ table: `HASH_FUNCTION(hash_function_name, hash_function_fuzzy_flag, hash_function_size)`

I have a question regarding the _shake_ hashes.

From the [documentation of the hashlib module:](https://docs.python.org/3/library/hashlib.html#shake-variable-length-digests)

> The shake_128() and shake_256() algorithms provide variable length digests with length_in_bits//2 up to 128 or 256 bits of security. As such, their digest methods require a length. Maximum length is not limited by the SHAKE algorithm.

Is it okay if we restrict the digest size of the _shake_ hashes we store to the database? We will set the fixed size to 128 and 256 bits for shake_128() and shake_256() respectively to achieve maximum security.

Otherwise we can set `hash_function_size = NULL`. If this is the case, we should include a relevant `shake_digest_size_parameter` to the `scan` command, which will determine the digest size of a _shake_ hash value, if such a value is calculated in a particular scan.

Personally, I prefer storing shake hashes using a fixed digest size to avoid making the `scan` command complicated.

**Comment by zvr** [comment]
In the first set, please also add the hashes from Software Heritage and xxhash.

We can ignore the ones with varying sizes for now.

**Comment by gkosm314** [comment]
Do you refer to SWHID? I aimed to save them at the `SWH_INFO(file_id, swh_id_core, swh_id_qualifiers)` table.
