### ISSUE TITLE
Implement "search" command

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2021-hashesDB#39]
Arguably the main functionality of the program is searching the database. I did not see an issue/task about that.

**Comment by gkosm314** [comment]
I planned to use the print command for this functionality.

Specifically, `print --hash -hash_value fc5e038d38a57032085441e7fe7010b0` would return the rows of the _HASH_ table where the hash value equals to `fc5e038d38a57032085441e7fe7010b0`.

The user would choose to print more information about the file, the origin and the Software Heritage data related to this hash through the `-view_file`,`-view_origin` and `-view_swh` parameters. These information would be retrieved from the _FILE_, _ORIGIN_ and _SWH_INFO_ tables with the help of foreign keys.

Have I misunderstood the purpose of the _search_ command?

**Comment by gkosm314** [comment]
The `search` command will only work on single files (which we will search using hash values and/or filenames as search criteria), right? Is this command supposed to somehow support folders/dictionaries?
