### ISSUE TITLE
Scan Github links

### ISSUE THREAD

**Issue by gkosm314** [eellak/gsoc2021-hashesDB#60]

**Comment by gkosm314** [comment]
I plan to use Github's Personal access tokens as the only acceptable form of authentication. This means no interface will provided to enter username and password.

**Comment by zvr** [comment]
Can you describe what does "Scan Github links" mean?

**Comment by gkosm314** [comment]
A possible scan target could be a Github repo. In this case, the scan command will download the repo's content at a specified location (locally) and then it will scan it in the same fashion it scans local files.

**Comment by gkosm314** [comment]
Perhaps it would be useful to create independent arguments for each type of scan target.
For example:
`scan -d test_database.db -c md5 -t /dir1/dir2 --github ellak/gsoc2021-hashesdb -download-location dir3`
would:
- scan the contents of the /dir1/dir2 directory
- download the contents of  ellak/gsoc2021-hashesdb, store them inside dir3 and scan them
